export const prompts = [
    "How are you feeling today?",
    "What are you grateful for?",
    "What do I know to be true that I didn't know a year ago?",
    "What distractions get in the way of being my most productive?",
    "When do I feel most in tune with myself?",
    "If someone described me,\nwhat would they say?",
    "What can wait until next week?",
    "How does every part of my body feel in this moment?",
    "What emotions am I holding on to?",
    "How can I detach or neutralize this emotion?",
    "Why am I feeling this way?",
    "What is causing these feelings?",
    "Have I tried to take my ego out of the situation?",
    "How can I detach my emotions from the behavior of others?",
    "Did I use healthy boundaries before I began feeling this way?",
    "What hurts right now? \nHow can I find relief?",
    "When I look in the mirror, \n what do I see?",
    "What are the things in my home that are the most “me”?",
    "What am I doing right now?",
    "What happened before I felt a shift in my mood?",
    "What kind of day are you having, and why?",
    "What's your favorite color and why?",
    "What's your favorite place and why?",
    "What's your favorite food and why?",
    "What's your favorite book and why?",
    "What's your favorite song and why?",
    "What's your favorite movie and why?",
    "What do you like to do? \nHow does it make you feel?",
    "Where are you happiest? \nDescribe that place.",
    "What's something you're good at? \nWhat makes you good at it?",
    "What do you consider to be your culture, and how do you feel about it?",
    "What would you change about yourself or your life? \nIs there a way for you to change it?",
    "What is your relationship like with various members of your family?",
    "If you have brothers or sisters, \nhow are you similar to them or different from them? What about with your friends?",
    "What are your views on religion?",
    "What keeps you up at night worrying? \nAre your worries realistic? Is there anything you can do about them?",
    "Do you have a philosophy of life? \nIf so, what is it? If not, what is your method for making important decisions?",
    "In what areas are you optimistic, \nand in what areas are you pessimistic?",
    "What are your most prized possessions?",
    "Who is someone you miss?",
    "What is something someone else has that you envy? \nDescribe it and your feelings about it.",
    "What is a book, movie, song, or television program that has influenced you, and how?",
    "What is a mistake people often make about you?",
    "What's something you disagree with about the way you were raised?",
    "What's your favorite food? \nDescribe it.",
    "What's your favorite season? \nDescribe it.",
    "What's your favorite place? \nDescribe it.",
    "What's your favorite color? \nDescribe it.",
    "Describe your dream job.",
    "Describe your dream man/woman.",
    "Describe your dream house.",
    "How would you like your life to be when you're older?",
    "What would be the guest list at your dream party? What would the various guests talk about?",
    "What magic power would you like to have? How would you use it? What would it feel like?",
    "If you won the lottery, \nwhat would you do?",
    "What's a country you'd like to visit? How do you imagine your time there?",
];
